names = input("Enter your first and last name ")
lname = input("Enter your last name ")
country = input("Enter your country of origin ")
profession = input("Enter the nature of your current job ")
email = input("Enter your email address ")
phone = input("Enter your phone number ")
city = input("Enter your current city of residence ")
address = input("Enter your mailing address")
print("=" *100)
print('Name: ', names)
print('Last Name: ', lname)
print('Country: ', country)
print('Profession: ', profession)
print('Email: ', email)
print('Phone: ', phone)
print('City: ', city)
print('Address: ', address)
